### ISSUE TITLE
请问能提供一下详细的环境配置吗？

### ISSUE THREAD

**Issue by yangtf983** [ZiqianZENG/VWS-PR#1]
您好，我现在使用 tensorflow-gpu 1.15.0 运行这个程序，出现很多警告，并且无法正常运行结束。请问能够告知一下具体的软件包版本？谢谢！

**Comment by ZiqianZENG** [comment]
We test on tensorflow-gpu 1.14.0. We did not test on tensorflow-gpu 1.15.0.
